name: Build ROM
on:
  workflow_dispatch:
    inputs:
      manifest_url:
        description: 'Manifest URL'
        required: true
        default: 'https://github.com/DerpFest-AOSP/manifest'
      device_tree:
        description: 'Device Tree'
        required: true
        default: 'https://github.com/TDD788/A21s-DevTree'
      device_name:
        description: 'Device Name'
        required: true
        default: 'a21s'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start
        run: |
          echo "Starting the build for ${{ github.event.inputs.device_name }}..."
          echo "Your Blur will be light and smooth!"
          
